_target_: cnos.model.sam.CustomSamAutomaticMaskGenerator
points_per_batch: 64
stability_score_thresh: 0.97
box_nms_thresh: 0.7
min_mask_region_area: 0
crop_overlap_ratio: null
segmentor_width_size: ${model.segmentor_width_size}
sam:
  _target_: cnos.model.sam.load_sam
  model_type: vit_h
  checkpoint_dir: /home/shruthi/Documents/Code/araas/src/pyaraas/python/pyaraas/tools/pose_estimation/cnos/datasets/bop23_challenge/pretrained/segment-anything
